# pre-commit configuration
#
# Uses https://pre-commit.com/
#
# Install with:
#   pre-commit install --install-hooks
#
# or for specific hook stages only:
#
#   pre-commit install -t pre-commit
#   pre-commit install -t pre-push
#   pre-commit install -t commit-msg
#   pre-commit install -t post-checkout
#
# Requires:
#   - rust (cargo & clippy in path)
#   - https://github.com/commitizen-tools/commitizen
#
# To run manually:
#   pre-commit run --all

repos:
  - repo: https://github.com/domodwyer/pre-commit
    rev: v3.4.1
    hooks:
      - id: rust-clippy
        stages: [commit, push]

      - id: rust-test
        stages: [commit, push]

      - id: rust-fmt
        stages: [commit, push]

      - id: rust-doc
        stages: [push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [commit, manual]
      - id: check-json
        stages: [commit, manual]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        stages: [commit, manual]
      - id: check-merge-conflict
        stages: [commit, manual]
      - id: mixed-line-ending
        args: ["--fix=no"]
        stages: [commit, manual]
      - id: no-commit-to-branch
        args: ["--branch", "master", "--branch", "main"]
        stages: [commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]