on: [push]

jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo fmt -- --check
      - run: cargo test --all-features

      # Clippy
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings